### ISSUE TITLE
The milliseconds time precision parameter is "ms", not "m"

### ISSUE THREAD

**Issue by contentfree** [logstash-plugins/logstash-output-influxdb#22]
From the Influxdb docs: "If you write data with a time you should specify the precision, which can be done via the time_precision query parameter. It can be set to either s for seconds, **ms for milliseconds**, or u for microseconds." 

Whereas this plugin validates time_precision as "m" for milliseconds. This leads to the incorrect precision in influxdb.

(Additionally, the default probably should match Influxdb's default of millisecond.)

**Comment by suyograo** [comment]
Fixed in #30
