### ISSUE TITLE
Add support for HTTPS via configuration

### ISSUE THREAD

**Issue by mikelaws** [logstash-plugins/logstash-output-influxdb#32]
Using the pr/29 branch, there doesn't appear to be an option to choose between http: and https:.  Using the InfluxDB hosted service, I was unable to POST data_points via HTTP.

After manually updating the plugin and rebuilding I was successfully able to POST via HTTPS.

**influxdb.rb:**
`@base_url = "https://#{@host}:#{@port}/write"`

**Comment by suyograo** [comment]
Fixed in #33
