### ISSUE TITLE
Maintainers needed for this plugin

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-influxdb#34]
We would love some help maintaining this plugin. Please comment on this issue if you have experience working with influxdb and/or this plugin and are ready to review and merge existing pull requests. Thanks much!

**Comment by timgriffiths** [comment]
Yeah why not, I would be interested in helping out

**Comment by IngaFeick** [comment]
Me too!

**Comment by suyograo** [comment]
Thanks folks!

**Comment by IngaFeick** [comment]
Thx! :)

**Comment by acchen97** [comment]
Thanks for the interest!  @IngaFeick I sent you an email.  @timgriffiths I don't have your email, can you please contact me at alvin@elastic.co?

**Comment by IngaFeick** [comment]
@acchen97 super, thanks!

**Comment by lukaslozovski** [comment]
Hi, I'd like to help with maintaining this plugin as well.

**Comment by zsserg** [comment]
@suyograo , what happened to this plugin? It seems to be not actively maintained any more despite the number of volunteers?

**Comment by acchen97** [comment]
@zsserg I saw the [issue](https://github.com/logstash-plugins/logstash-output-influxdb/issues/45) you filed, any other issues?

@IngaFeick is the maintainer of this plugin. Inga, can you please help here?

**Comment by zsserg** [comment]
Thanks for reply. 
The issue I reported should be closed with PR #39 which was submitted about 3 months ago...
There are also a couple of other useful PR that add nice functionality ( #40 , #46 )
All of them are waiting for 1-2 months or so for now. This suggest that the development of the plugin was paused for some reason. 
Will be happy if it's not the case.

**Comment by zsserg** [comment]
Hi!
Any updates on these issues?

**Comment by meritus** [comment]
Hey, I submitted #39 and can lend a hand to maintaining if it is needed.

**Comment by acchen97** [comment]
@meritus thanks for your request, I'd love to chat with you via email. Can you please send me a note at alvin@elastic.co?

**Comment by discoduck2x** [comment]
@zsserg @meritus @acchen97 
So is anything happening with this now?

**Comment by zsserg** [comment]
I just forked it & will use my own branch (after integration of some patches) until this one gets back to life. I'm unable to assist in maintenance as I am a zero-level Ruby coder (yet). =(

**Comment by rileytg** [comment]
ill help if someone wants to point me in a direction?

**Comment by sheinbergon** [comment]
@suyograo are you still interested in help. Would be much interested in contributing code and handling PRs/issues as well

**Comment by cshimegi** [comment]
@suyograo @sheinbergon 
Sorry to ping you guys now.
I'm wondering if this repo is still under maintenance or not. If not, please show some messages on README.md or somewhere. I actually don't understand lots of must-fix PRs there but no maintainer helps review or do something to keep the repo updated.
