### ISSUE TITLE
InfluxDB doesnt pick up metrics sometimes 

### ISSUE THREAD

**Issue by ankush819** [logstash-plugins/logstash-output-influxdb#52]
I use logstash-output-influxdb plugin to send my metrics directly to influxDB. Sometimes the nohup agent running logstash gets killed and when I restart the agent again, influx wont pick up the metrics spontaneously most of the times. It has a buffer time of 15 mins - 2 hrs after which it starts showing these metrics on grafana. 

I did a tcpdump on my monitoring server and I can see packets getting sent to 8086 port. So the metrics IS reaching the monitoring server but somehow influx wouldn't show that in this window. 

I am not sure if it is even related to this plugin. Please redirect me to the right place if it isn't. 

On a side note, we also another setup in which the logstash metrics are sent to the riemann server using logstash-riemann plugin. We don't see this issue there.

**Comment by andrewvc** [comment]
This should be fixed in v 5.0.0 Thanks to #55. I'm going to close this issue given that. If you continue to encounter an issues please open a new issue. Thanks :)
