### ISSUE TITLE
Issue with data_points and tags

### ISSUE THREAD

**Issue by vaibhavmoengage** [logstash-plugins/logstash-output-influxdb#78]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by vaibhavmoengage** [comment]
I am using logstash to publish metrics to influxdb. I don't want to blacklist any metric,However i would want to use some of them as tags.Under data_points config what do i have to do to pass all the metrics?

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
